### ISSUE TITLE
[BUG] - Dont work , after Nebula Multiplayer API update today?

### ISSUE THREAD

**Issue by AliSwitch** [kremnev8/DSP-Mods#101]
I don't know if I'm the only one having this problem

**Comment by LVincent555** [comment]
I also encountered the same problem

**Comment by writzthecat** [comment]
same here....

**Comment by kremnev8** [comment]
Thanks for your report. I will look into it.
There is a temporary workaround, if you don't use nebula: revert nebula API to 1.3.1

**Comment by kremnev8** [comment]
Issue fixed in v1.6.4
