### ISSUE TITLE
[Enhancement] - Add Giga charging station

### ISSUE THREAD

**Issue by Vladyslav-Krot** [kremnev8/DSP-Mods#14]
I think it will be appropriate to add giga charging station in scope of this mode because they always use in pair

**Comment by kremnev8** [comment]
Do you mean energy exchanger building, the one that charges/discharges batteries? Then I think its actually of out of scope of that mod. And even if I were to add them, what kind of changes are you looking for? Because as far as I can tell placing more of them solves all problems.
