### ISSUE TITLE
[BUG] - Errors when dismantling prebuilds using DragRemoveBuildTool.

### ISSUE THREAD

**Issue by JamieRCHI** [kremnev8/DSP-Mods#15]
**Describe the bug**
Got IndexOutOfRangeException.

**To Reproduce**
1. Go to Delete option.
2. Click on the Area Selection button.
3. See error

**Log files**
[output_log.txt](https://github.com/kremnev8/DSP-Mods/files/7174378/output_log.txt)

**Comment by kremnev8** [comment]
This issues seems to only happen if prebuilds are in selection. Should be fixed in the next release.

**Comment by JamieRCHI** [comment]
Thank you.
