### ISSUE TITLE
[BUG] - BlueprintTweaks does not have Chinese translation

### ISSUE THREAD

**Issue by muink** [kremnev8/DSP-Mods#17]
**Describe the bug**
The blueprint descriptions is lost in Chinese mode
For example: `Blueprint size` `Foundations` `Recipes` ...

**Screenshots**
| English | Chinese |
|----|----|
| ![en](https://user-images.githubusercontent.com/7929014/135573926-3f213e95-a7e4-4473-9319-1659e143b0cf.png) | ![ch](https://user-images.githubusercontent.com/7929014/135573946-35864358-15a1-4892-a7ed-ff3968d70cdf.png) |

**Comment by kremnev8** [comment]
The reason for that is that I don't have strings for Chinese. If you want to help, you can find original strings [here](https://github.com/kremnev8/DSP-Mods/blob/b0bda5e237b0c1e35345655de02b7624d2562420/Mods/BlueprintTweaks/BlueprintTweaksPlugin.cs#L100). If you can translate all of them, I can easily add Chinese support.

**Comment by muink** [comment]
Thanks a lot. I'm happy to help
I will take a moment to translate these :D

**Comment by muink** [comment]
The translation is done \o/
[BlueprintTweaksPlugin.cs.txt](https://github.com/kremnev8/DSP-Mods/files/7271516/BlueprintTweaksPlugin.cs.txt)

**Comment by kremnev8** [comment]
Thanks. I will add it, and release a version soon.

**Comment by kremnev8** [comment]
Version 1.2.2 now supports Chinese language.

**Comment by muink** [comment]
Thank you lol
