### ISSUE TITLE
[BUG] Giga Stations - VfAudio.Create

### ISSUE THREAD

**Issue by AandD** [kremnev8/DSP-Mods#18]
Problem with level upgrade belts and sorters. With last patch some changes with method VFAudio.Create were made.
StationUpgradePatch.cs at line 95 throws exception Missing method exception VFAudio.Create.
Thanks.

**Comment by kremnev8** [comment]
Thanks for reporting. This is easy to fix. Will do so soon.

**Comment by Cacilia-11** [comment]
Thanks for the great mod.
I'm waiting for the support.

**Comment by kremnev8** [comment]
Fixed.

**Comment by Cacilia-11** [comment]
Thank you from the bottom of my heart
