### ISSUE TITLE
"Missing Field Exception" with AdvancedMiner in DSP 0.8.22.9331

### ISSUE THREAD

**Issue by milesvdw** [kremnev8/DSP-Mods#19]
Verified on multiple machines & steam accounts. AdvancedMiner seems to be the problem. When loading a game in which advanced miner had already been researched/built (not sure which was the key here).

Error is:
Missing Field Exception: Field 'RecipeCheck.abnormalityCheck' not found

Please let me know if you need any more information. Also happy to help out, I'm a software engineer myself but obviously unfamiliar with how your mod works.

**Comment by kremnev8** [comment]
I'm aware of this issue. It will be fixed in the next release

**Comment by kremnev8** [comment]
Currently there is a workaround it. You can Install AchievementsEnabler https://dsp.thunderstore.io/package/PhantomGamers/AchievementsEnabler/

**Comment by arlight1** [comment]
Can confirm installing the AchievementsEnabler mod fixes the error message, thanks for the workaround...it's hard to play without this mod considering how small the range normally is of the miner we have already available to us.

Thanks again.

**Comment by kremnev8** [comment]
Also should be fixed in the latest release.
