### ISSUE TITLE
Having trouble showing the AdvancedMiner

### ISSUE THREAD

**Issue by tommynanny** [kremnev8/DSP-Mods#2]
I followed the manual installation process of the AdvancedMiner. I place all the files in "Dyson Sphere Program\BepInEx\plugins\DSPAdvancedMiner", but there is no building option of "Mining drill Mk.II" under my replicator panel. So I also place a copy of "DSPAdvancedMiner.dll" in "Dyson Sphere Program\BepInEx\plugins\" as well, but still no luck. I am not sure if this has anything to do with the fact that I have unlocked the "High-speed assembling processes" prior to the installation of this mod. (meaning I have to manually unlock the "High-speed assembling processes" in order to get the  "Mining drill Mk.II", and in my case, I need to start a new game )

![Untitled](https://user-images.githubusercontent.com/22390882/107845986-1e98ce80-6dae-11eb-966f-c5182e5e5017.png)
![1](https://user-images.githubusercontent.com/22390882/107845987-1e98ce80-6dae-11eb-9337-86c3092593f6.png)
![2](https://user-images.githubusercontent.com/22390882/107845988-1f316500-6dae-11eb-944e-651e9ae4344c.png)
![3](https://user-images.githubusercontent.com/22390882/107845996-2f494480-6dae-11eb-9249-884f9514f90c.png)

**Comment by kremnev8** [comment]
First of all remove dll from plugins folder, it should be in a dspAdvancedMiner folder. Also new miner should be available in old saves too. Please can you attach a log file from BepInEx folder.

**Comment by kremnev8** [comment]
And generally each dll has to be in its own folder

**Comment by kremnev8** [comment]
Do you still have the problem, or is it solved?

**Comment by tommynanny** [comment]
Sorry for the late reply, I have always placed the dll directly inside the plugins folder without any subdirectory and all my other plugins work as expected before. According to the log file shown below, the "DSP Advanced miner 0.1.0.2" should have been loaded. here is the content of the "Dyson Sphere Program\BepInEx\LogOutput.log" file, but I just can't seem to find the "Mining drill Mk.II". I was wondering if there maybe a plugin conflict?

```[Message:   BepInEx] BepInEx 5.4.5.0 - DSPGAME
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 2.0.50727.1433
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 17 plugins to load
[Warning:   BepInEx] Skipping [DSP Advanced miner 0.1.0.2] because a newer version exists (DSP Advanced miner 0.1.0.2)
[Info   :   BepInEx] Loading [LDBTool 1.7.0]
[Info   :   BepInEx] Loading [WaterElectrolysis 1.0]
[Info   :   BepInEx] Loading [QTools 3.2]
[Info   :   BepInEx] Loading [ShowBirthStar 2.0]
[Info   :   BepInEx] Loading [Trash Plugin 1.1]
[Info   :   BepInEx] Loading [物品叠加 By:小莫 1.0.0]
[Info   :   BepInEx] Loading [AdvancedBuildDestruct 1.0.5]
[Info   :   BepInEx] Loading [More Replication 1.2.1]
[Info   :   BepInEx] Loading [Galaxy Vein Early View 2.0.0.0]
[Info   :   BepInEx] Loading [Vein Detail View 1.0.0.1]
[Info   :   BepInEx] Loading [Copy Inserters Plug-In 1.0.0.0]
[Info   :   BepInEx] Loading [More Smelters 0.1.0]
[Info   :   BepInEx] Loading [More Storage 0.1.2]
[Info   :   BepInEx] Loading [DSP Advanced miner 0.1.0.2]
[Info   :   BepInEx] Loading [Miner Info Plugin 1.0.0.0]
[Info   :   BepInEx] Loading [Upgrade Fix 1.0.0.0]
[Message:   BepInEx] Chainloader startup complete
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type System.Exception and name PrepForRemoting and parameters 
```

**Comment by kremnev8** [comment]
First of all placing mods in their own folders is not required for most mods, but recommended. As for mine it is required. Another issue, you still have two DSPAdvancedMiner.dll in plugins folder. Remove one in plugins and put archive contents in DSPAdvancedMiner folder.

**Comment by kremnev8** [comment]
Also this log is not full. Please attach full log(After game loads to main menu), after doing what i asked you to do.

**Comment by tommynanny** [comment]
it works now. I have removed the "DSPAdvancedMiner.dll" and placed all files in the folder named "DSPAdvancedMiner". 
![image](https://user-images.githubusercontent.com/22390882/107856557-eb2e6200-6df6-11eb-9c25-2a39aec6dd83.png)
Thank you so much, I should follow the instruction strictly ;) 
nice mod bro 
![image](https://user-images.githubusercontent.com/22390882/107856583-0f8a3e80-6df7-11eb-83fb-61bb586c6f12.png)
