### ISSUE TITLE
[Enhancement] Add the ability to modify belt hints

### ISSUE THREAD

**Issue by aekoch** [kremnev8/DSP-Mods#20]
Using this mod, it is possible to change the inputs/outputs of logistics stations and the recipes used by buildings, but it is not possible to change belt hints.  For example, changing my smelters from iron to copper, I would like to change the iron ore and iron bar belt hints to copper ore and copper bar hints.

**Comment by kremnev8** [comment]
This feature was added in version 1.3.1
