### ISSUE TITLE
[BUG] - "PickerExtensionSystem is not loaded" when selecting recipe in particle accelerator

### ISSUE THREAD

**Issue by CaptainHorse** [kremnev8/DSP-Mods#21]
**Describe the bug**
"PickerExtensionSystem is not loaded" error upon trying to select Particle Accelerator recipe after updating to version with CommonAPI changes.

**To Reproduce**
1. Build a particle accelerator
2. Open it's UI
3. Try to select recipe
4. Get error

**Expected behavior**
List recipes available

**Log files**
[Pastebin link](https://pastebin.com/eaL9DY17)

**Screenshots**
![error screenshot](https://user-images.githubusercontent.com/14197772/142682107-cdac20d2-b119-4db4-b25f-5175118837d7.png)

**Additional context**
*Neighs*
Noticed AssemblerUI was causing error in log with current version of the game, disabled it but no effect on this mod and thus issue.

**Comment by kremnev8** [comment]
Thanks for reporting. I will fix this soon. Also please note that Issues related to CommonAPI better be reported at its repo

**Comment by kremnev8** [comment]
Should be fixed with CommonAPI version 1.0.1
