### ISSUE TITLE
[BUG] - LDBTool Missing

### ISSUE THREAD

**Issue by JamieRCHI** [kremnev8/DSP-Mods#25]
**Describe the bug**
Haven't played in awhile and for some reason I get an error saying LDBTOOL is missing.
The mod manager said it was still installed.

I tried re-installing it with the mod manager and that didn't work.
For some reason the DysonSphereModMan manager thinks it is installed.
All the other mods required by the BluprintTweeks mod are installed correctly by the mod manager when BlueprintTweeks mod is installed.

I did manage to find it in the AppData\Roaming\r2modmanPlus-local\DysonSphereProgram\cache folder so I copied it to where it should be in AppData\Roaming\r2modmanPlus-local\DysonSphereProgram\profiles\Default\BepInEx\plugins.
Then everything worked correctly.

I was wondering if there was a way the BlueprintTweeks mod could check for this when it is installed and install the LDBTool.dll file if it is not found? Or maybe add a note on the Thunderstore site to inform people that they may need to manually install this dll even if they are installing the BluePrintTweeks mod with the Mod Manager?

I am not sure if anyone else has seen this issue or not. Maybe it's just me.

**Comment by kremnev8** [comment]
I'm not sure this bug has anything to do with my mod. This looks like a mod manager bug. Please report that to the mod manager issues.

**Comment by JamieRCHI** [comment]
Thanks. I opened a new issue for the R2modmanPlus mod manager.
https://github.com/ebkr/r2modmanPlus/issues/683
