### ISSUE TITLE
[Enhancement] Allow to paste filters and recipes not learned yet

### ISSUE THREAD

**Issue by zxcvbnm3057** [kremnev8/DSP-Mods#27]
Would you mind to add a future which can paste 
locked setting of splitter and sorter and paste locked recipe setting? This will help a lot while paste a blueprint and build it before unlock all require technology, for example, start to build a market before unlock all red matrix technologies. Item wouldn't appear until player get the recipe so setting of selector won't be a bug. And for assembling machine maybe just force set the recipes but add a locked check in recipe's original material requirements check will work. Thank you for this amazing mod!

**Comment by zxcvbnm3057** [comment]
And could you add a calculus in blueprint selector screen, such as add a text in red show the short building.

**Comment by zxcvbnm3057** [comment]
BTW, please must forgive my poor English

**Comment by kremnev8** [comment]
Ok, so if I understood you correctly you want to be able to paste blueprints which contain locked items. Unfortunately right now I have little free time. But when I do have time, I will look into this.

**Comment by zxcvbnm3057** [comment]
yeah, that's what I mean. Thanks!

**Comment by zxcvbnm3057** [comment]
In addition, can the scope of application of the blueprint be displayed on the blueprint details page? If so, it's best to make the blueprint support partition construction. Some old computers can't lay the whole large blueprint at one time. In addition, it seems that the Caton of the selected blueprint can be realized through caching by comparing the modification time and cache date of the last blueprint file

**Comment by kremnev8** [comment]
With version 1.4.0 locked recipes are persisted. As for the other request can you please open a different issue for it and explain more clearly.

**Comment by zxcvbnm3057** [comment]
Thanks for your wonderful mod, now I can pastes blueprints without worry about will there be an error! I also put forward my other suggestions separately in different issuses.
