### ISSUE TITLE
[BUG] [GigaStations] - Hurricane Stone Forest models replaced

### ISSUE THREAD

**Issue by octarine-noise** [kremnev8/DSP-Mods#28]
Some of the terrain models of the Hurricane Stone Forest planet type are replaced by ones from GigaStations.

Planet without the mod:
![without mod](https://i.imgur.com/pCjNjt6.png)

Planet with the mod:
![with mod](https://i.imgur.com/OU2eUZk.png)

**Comment by kremnev8** [comment]
I already know about this bug, but still thanks for reporting. I will fix this as soon as I have free time.

**Comment by kremnev8** [comment]
For now you can just cover the planet with foundations and you should not have any troubles.

**Comment by kremnev8** [comment]
Version 2.2.4 has this issue fixed.
