### ISSUE TITLE
Error in new DSP release 0.9.24

### ISSUE THREAD

**Issue by 5thHorseman** [kremnev8/DSP-Mods#29]
Error received in 0.9.24
![bptweaks](https://user-images.githubusercontent.com/5622822/150455796-f1b30c46-73f8-42cf-be98-546cf86f022c.png)

Occurs when placing any blueprint.

**Comment by Yarmoor** [comment]
Occurs when forcing a blueprint placement

**Comment by kremnev8** [comment]
Thanks for reporting. Will fix soon.

**Comment by lcarter89** [comment]
Not getting the error but mod not working under new game version for me either. Such a great mod, can't wait for the update.
Thanks so much.

**Comment by kremnev8** [comment]
Just uploaded v1.4.0 should fix these errors.

**Comment by olet42** [comment]
> Just uploaded v1.4.0 should fix these errors.

v 1.4.0 is close to a year old?

**Comment by kremnev8** [comment]
v1.4.0 of what? This is issue is for BlueprintTweaks.
