### ISSUE TITLE
Feature Request - Implement StackSizeEditor

### ISSUE THREAD

**Issue by JamieRCHI** [kremnev8/DSP-Mods#35]
Is there a chance you could make an updated version of the StackSizeEditor mod by Taki707?
Would it take much work? Thanks.

**Comment by kremnev8** [comment]
From a quick look it seems that would take me at least a whole day to figure out what's going on there and fix it. And since there seems to be a few alternative mods, I'm not sure if that would be worth it.

**Comment by JamieRCHI** [comment]
This is the only mod that allows changing the stack size of each individual item separately. All the others make all the stack sizes the same. Different things need different stack sizes. 

Thanks anyway. I suppose it's time for me to do some programming again and look into it myself.
Thanks for looking at this.
