### ISSUE TITLE
[Enhancement] - Allow colors to display when placing Blueprint with foundations instead of blue rectangle..

### ISSUE THREAD

**Issue by JamieRCHI** [kremnev8/DSP-Mods#36]
I use colored foundations to make pictures such as arrows and text that can be seen from the Planet view easily. Also these blueprints make it easier to make colored lines along the meridian and equater lines.

Would it be possible to show the colors when placing the blueprint instead of the blue ghosts?

Currently everything in the blueprint is shown in blue which makes it impossible to orient a blueprint consisting of only foundation pieces. 

Also I noticed that when disabling foundations, the checkmark is not removed in the dialog when clicked on. Thank you.

**Comment by kremnev8** [comment]
Unfortunately, but blueprint preview shader that game uses does not support colored foundations. As such this would be very hard to add. (I would have to reverse engineer their shader, which is a hard thing to do, and then modify it to display colors.). As such I'm unlikely to take this endeavor.
