### ISSUE TITLE
BetterMachines LOD mismatch at MK2 & MK3 chemical plant.

### ISSUE THREAD

**Issue by Gabesz850110** [kremnev8/DSP-Mods#39]
Hello Kremnev8!

First I have to say, pretty amazing mod you made. Better Machines, better storage, useful af.
I would like to raise your attention, that the MK2 & MK3 Chemical Plants drawing the lowpoly LOD to early. It making a mismatch if you zoom out a little bit. At middle zoom, the building already showing the lowpoly models too early. It also jumping (visionaly) one tile, what makes difficult to build, especialy when you drag multiple buildings, for example to fill the sorters at bigger designs.

Is there a possibility to fix that issue?
Not a big problem, just a small step towards perfection.

Thanks for the reply.
Best wishes.

**Comment by kremnev8** [comment]
Yes, this should be easy to fix. Regarding LOD switch distances, as far as I know vanilla uses same distance.

**Comment by Gabesz850110** [comment]
Thank you for the fast response.

In that case, we waiting for the hotfix :)

**Comment by kremnev8** [comment]
Should be fixed in v1.0.6. You will also notice that now LOD's look much closer to high poly model.

**Comment by Gabesz850110** [comment]
I've tested it! Works like a charm :)

Thanks for the fast update, you're awesome!!!
