### ISSUE TITLE
Spray Coater pushed out of keybinds bar

### ISSUE THREAD

**Issue by darkedone02** [kremnev8/DSP-Mods#40]
While you add in new content, some others that are in the game got pushed out of the keybinds. it will be nice by default you moved the Spray Coating to somewhere else, let say gathering.

**Comment by kremnev8** [comment]
Do you mean you build bar?

**Comment by kremnev8** [comment]
You have rebind build bar for a reason. You can rebind it yourself.

**Comment by kremnev8** [comment]
Please check this mod readme. You already have it installed. https://dsp.thunderstore.io/package/kremnev8/RebindBuildBar/

**Comment by darkedone02** [comment]
> Do you mean you build bar?

Yes, hotbar key is what i ment.

**Comment by kremnev8** [comment]
Unfortunately I can't place everything by default, as there is not enough space in there. As such I won't be doing this. RebindBuild bar covers this issue perfectly.
