### ISSUE TITLE
[BUG] - belts construction line template lost with terrain elevation

### ISSUE THREAD

**Issue by pilow90** [kremnev8/DSP-Mods#42]
**Describe the bug**
minor bug since it doesn't break functionality.

when you select a belt to place on the grid map, if the terrain is high (like mountains or elevated terrain) the template line (white line that draws how long you want to place the belt line) goes under the elevated terrain texture and is no longer visible, you can build the belt tho, it seems to work as intended on flat terrain or foundations.

**To Reproduce**
1 - select any belt from MK1 to MK4.
2- draw a construction line under an irregular terrain.

**Additional context**
replicate this bug running this mod only with dependencies.
also tried running only dependencies with this mod disabled and wasn't able to replicate the bug.

![2022-02-09 03_23_17-Dyson Sphere Program](https://user-images.githubusercontent.com/48377236/153165721-59c63cc3-c8eb-4b5f-9a29-96b91dfff9cd.png)

**Comment by kremnev8** [comment]
This minor issue is caused by my replacement shader for this UI element. I'm not planning on trying to figure out why this happens, so this is unlikely to be fixed.
