### ISSUE TITLE
GroundSubstation

### ISSUE THREAD

**Issue by Lt-Sparky** [kremnev8/DSP-Mods#43]
No longer shows visual of object in game and when trying to place a new one the following error screen pops up...
![groundpower](https://user-images.githubusercontent.com/85095233/153735281-2d9718e0-162e-4a75-b3d4-a39ac4c0f6cd.jpg)

**Comment by kremnev8** [comment]
Unfortunately Unity project files for Ground Substation were lost, so I'm unable to update or maintain the mod.
