### ISSUE TITLE
How will the additional information added by this module be saved?

### ISSUE THREAD

**Issue by yunying61** [kremnev8/DSP-Mods#45]
# 该模块添加的附加信息将如何保存?

en:
Is additional blueprint information saved directly to TXT file?
If the blueprint system is updated in the future, can the information saved by this mod be used? Or if it interferes with the identification of the new blueprint system.

zh:
额外的蓝图信息是直接保存到txt文件中的吗？ 
如何未来蓝图系统更新了，那这个mod保存的信息能否使用？或者会不会干扰新蓝图系统的识别。

**Comment by kremnev8** [comment]
Information is written to the end of blueprint file and does not interfere with vanilla functionality, with mod or without it. If devs update their blueprint data structure this mod also will not break, as I don't change BP version, just check if there is more data.

**Comment by yunying61** [comment]
> Information is written to the end of blueprint file and does not interfere with vanilla functionality, with mod or without it. If devs update their blueprint data structure this mod also will not break, as I don't change BP version, just check if there is more data.

Thanks for your answer, this mod is so great!
