### ISSUE TITLE
[Enhancement] - Default cursor location selection

### ISSUE THREAD

**Issue by Chemie99** [kremnev8/DSP-Mods#47]
Be able to set the default cursor position for Blueprint placement.  It seems to default to lower left but I would prefer center but to get to center, I have to hit TAB 4 times....
or could it remember last selected?

**Comment by kremnev8** [comment]
Thanks for your suggestion. If I have time, I will look into implementing this.

**Comment by kremnev8** [comment]
This feature was added in v1.5.3

**Comment by Chemie99** [comment]
Great!
