### ISSUE TITLE
[BUG] BlueprintTweaks - Cannot change Belt Hints when creating or editing blueprints

### ISSUE THREAD

**Issue by AlJoelson** [kremnev8/DSP-Mods#49]
**Describe the bug**
Nothing displays under the "Belt Hints" submenu when creating or editing blueprints, meaning that belt memos cannot be changed.

**To Reproduce**
1. Copy a belt with an active belt memo (or select a blueprint with one).
2. Check under the Belt Hints submenu.
3. Nothing displays.

**Expected behavior**
Should be able to see the active belt memos and be able to swap them for other icons.

**Log files**
[LogOutput.log](https://github.com/kremnev8/DSP-Mods/files/8698872/LogOutput.log)

**Screenshots**
![beltmemo](https://user-images.githubusercontent.com/6069951/168563814-e3fe5098-ac45-4807-a2b7-da28c90960a6.jpg)

**Additional context**
In testing possible causes, I've also tried running the game with only the BlueprintTweaks mod active (and its prerequisites).

**Comment by kremnev8** [comment]
Fixed in v1.5.4
