### ISSUE TITLE
[Bug] Fix stack size being equal to 1000

### ISSUE THREAD

**Issue by Vassi** [kremnev8/DSP-Mods#5]
First of all, I love this mod, thank you so much! After my first vanilla playthrough I was definitely convinced that advanced versions of the miner and smelter would be epic, and the modding community came to my rescue.

My request: I like to automate the creation of all my buildings, usually into a box with only two-five slots left open depending on the building. As I arranged this for the advanced miner, with only one box open (so I could see what it's stack size was) I came back to find my processors depleted as it just kept stacking into the 300s lol.

Would it be possible to limit the stack size to ~50-100 or even make it configurable like the range?

Thank you for your work!

**Comment by kremnev8** [comment]
Oh. That one. Yes in the old version stacksize was broken and set to 1000(It was a bug in my registering library). Today a new bug was reported, so I will update my registry library, it should fix this bug.

**Comment by kremnev8** [comment]
Should be fixed in the latest version. Please make sure to separate those miners before installing the update, as I'm not certain if you lose items over new stack limit.
