### ISSUE TITLE
[BUG][BlueprintTweaks] - Mirroring a splitter does not update its input/output ports on UI

### ISSUE THREAD

**Issue by MichaelKim0407** [kremnev8/DSP-Mods#54]
**Describe the bug**
When a splitter in a blueprint is mirrored, the UI for that splitter (where you can choose input/output priority) still shows the original orientations.

**To Reproduce**
See screenshot below

**Expected behavior**
The directions in the UI should also be mirrored.

**Screenshots**
![1366540_20220917022601_1](https://user-images.githubusercontent.com/2630527/190850189-0295c24d-daf1-406d-ad00-f08ede2b0d4e.png)

**Comment by kremnev8** [comment]
Thanks for reporting this. Unfortunately I don't have a lot of time right now for modding this game, so I can't say when I will get to fixing this.

**Comment by kremnev8** [comment]
The issue should be resolved in v1.6.1
