### ISSUE TITLE
[BUG][BlueprintTweaks] - Not working in 0.9.27

### ISSUE THREAD

**Issue by horeaper** [kremnev8/DSP-Mods#56]
**Describe the bug**
Interface not shown, keyboard shortcut no response, it looks as if the plugin is not loaded.

**Comment by kremnev8** [comment]
I'm aware. Fix will come very soon

**Comment by kremnev8** [comment]
Fixed in v1.5.7

**Comment by horeaper** [comment]
Tested in latest update 0.9.27.14553, works as expected ^_^
(This mod is really a life saver!)
