### ISSUE TITLE
After today's update, can no longer open the stations UI

### ISSUE THREAD

**Issue by TakeyaSaito** [kremnev8/DSP-Mods#57]
Station UI simply no longer opens after the game updated, just opens own inventory and nothing else.

**Comment by kremnev8** [comment]
Thanks for reporting. I will look into this as soon as possible.

**Comment by kremnev8** [comment]
Hm. I just did a test, and I can't reproduce this. The mod seems to be working perfectly fine. Can you please provide more info?

**Comment by TakeyaSaito** [comment]
> 

Oh I guess its probably another outdated mod that is interfering with it. I suspect it might be the stack sizes mod I am using. ignore my report then ^^
