### ISSUE TITLE
[BUG] - Power Exchanger not showing when mod active

### ISSUE THREAD

**Issue by Wolphin5** [kremnev8/DSP-Mods#59]
**Describe the bug**
While mod is enabled, on version 0.9.27.14659, under Transportation, the Power Exchanger is not showing up at all.

**To Reproduce**
Steps to reproduce the behaviour:
On the interface, with plugin enabled, in the list of Transportation, it only shows the 3 regular and 3 Giga Transport Hubs.

**Expected behavior**
It should show 7 items, the 6 Hubs and the Power Exchanger.

**Screenshots**
With Mod Enabled:
![image](https://user-images.githubusercontent.com/44385601/193377415-ec57550c-916e-424e-9be1-760deae564f1.png)

Without Mod:
![image](https://user-images.githubusercontent.com/44385601/193377490-97a5affb-cd51-4db4-9f3c-b8ee9125a651.png)

**Additional context**
This issue has just started recently with the updates.

**Comment by Wolphin5** [comment]
Wondering if the new "Logistics Distributor" is causing the issue...  as it is a new item in the first spot...

**Comment by kremnev8** [comment]
Thanks for reporting. I will fix this as soon as possible. There is a workaround for this. You can use Rebind Build Bar to manually add the item to the build bar.

**Comment by kremnev8** [comment]
Fixed in v.2.3.2
