### ISSUE TITLE
[Suggestion] Configuration of scrollbar with more than 5 slots

### ISSUE THREAD

**Issue by jordan30001** [kremnev8/DSP-Mods#6]
Would it be possible to add the "add scrollbar if more than 5 slots" as a config option.
This will be useful for users that have large monitors that can fit more slots on screen at once thus less scrolling is needed.

**Comment by kremnev8** [comment]
I can make that minimum amount configurable. Would that be sufficient?

**Comment by kremnev8** [comment]
Another thing i can actually do is arrange slots in a grid.

**Comment by jordan30001** [comment]
I think both would be fine, however, arrangement in a grid may be better for a majority of users

**Comment by kremnev8** [comment]
Both features were released with version 2.1.1
