### ISSUE TITLE
[BUG] - Mirroring blueprint escapes the blueprint box. 

### ISSUE THREAD

**Issue by NBKRedSpy** [kremnev8/DSP-Mods#60]
Update:  Updated Reproduction steps.
Workaround:  Don't press Shift+R.  Just use R if rotating.

**Describe the bug**
When in the "place blueprint" mode, pressing Shift+T will cause the blueprint to be offset outside of the blue placement UI.

** Versions
DSP:  0.9.27.15033
Mod version: 1.5.7

**To Reproduce**
1. Go to blue prints (0)
2. Double click a blueprint
3. Press Shift+R (not just R)
4. Press Shift+t

Result:  The ghost buildings will be outside of the blue placement box.  I think it is relative to the anchor point.

**Expected behavior**
Expected the flipped blueprint to stay int he blueprint box.

User impact:  For very large placements, this requires the user to zoom out enough to have the mouse on the original blue box and to still have the actual placement estimate on the screen.

**Log files**
I don't see any log files in BepInEx folder.  I'm launching through r2modman, so maybe related?  I searched the r2modman install dir and didn't find any there.

**Screenshots**
<img width="219" alt="BlueprintEscape" src="https://user-images.githubusercontent.com/54865934/199780702-4758d9da-ff71-4d21-910f-ca4df71f21a6.png">

**Comment by kremnev8** [comment]
Hm. Maybe this issue is related to anchors? I will look into this later.

**Comment by NBKRedSpy** [comment]
Ok, found the actual reproduction steps.  Updated OP.

Have to press Shift+R and then Shift+T.

**Comment by kremnev8** [comment]
Issue fixed in v1.5.11
