### ISSUE TITLE
[Enhancement] Allow specifying a recipe for blueprints without any

### ISSUE THREAD

**Issue by LordMike** [kremnev8/DSP-Mods#62]
I'm looking at a number of generic "template" factories with f.ex. 20 assemblers, and belts for 2 inputs and 1 output. These templates do not have any recipe on them, so I can't currently edit the templates recipe before placing :/

I'm amazed by all the other stuff I can do though, so I hope this can be added as well :)

I imagine that any assembler, smelter or chemical plant without a recipe, would be grouped in the recipes section, with maybe a dotted-box signifying an empty assembler/smelter/chemical plant?

Clicking this should open the recipe menu as usual.

**Comment by kremnev8** [comment]
Unfortunately I do not take feature requests at the moment.

**Comment by kremnev8** [comment]
(Reopening since I'm taking feature requests right now)

**Comment by kremnev8** [comment]
Feature implemented in Blueprint Tweaks v1.6.0
