### ISSUE TITLE
[Enchacement]Add mod shortcuts to an overlay CtrlC/CtrlV mode.

### ISSUE THREAD

**Issue by Layarion** [kremnev8/DSP-Mods#65]
I'd like it if the panel on the right, perhaps at the bottom of it, showed the keys/shortcut keys. like in the image.

If you don't want it to take up space, then consider doing the same thing, but with just one that says "mod info" and when you mouse over it, a tooltip goes into detail or something.
![image](https://user-images.githubusercontent.com/7917992/230689948-315e9c05-3ab8-422f-995f-6320c860ad7d.png)

**Comment by kremnev8** [comment]
Unfortunately I do not take feature requests right now.

**Comment by kremnev8** [comment]
(Reopening since I'm taking feature requests right now)

**Comment by kremnev8** [comment]
Feature implemented in Blueprint Tweaks v1.6.0
