### ISSUE TITLE
[BUG] Yellow square, don't know how to get rid of it.

### ISSUE THREAD

**Issue by Layarion** [kremnev8/DSP-Mods#66]
**Describe the bug**
After messing around and pasting part of Ludu's toolbox, i hit CtrlZ (i think), and now this yellow square is on the ground and i can't get rid of it.

I don't yet know how to repeat it, and i can't seem to select it either with the BP menu or anything.

**Log files**
Please upload log file from BepInEx folder to help solve issue
[LogOutput.log](https://github.com/kremnev8/DSP-Mods/files/11182055/LogOutput.log)

**Screenshots**
(https://i.imgur.com/Z5o5ePj.png)

**Comment by kremnev8** [comment]
Can you please provide the blueprint that you have pasted?

**Comment by Layarion** [comment]
I'm not even sure what caused it, so next time it happens i'll try to recall more of what i was doing. here's the BP i was using: https://www.dysonsphereblueprints.com/blueprints/ludus-toolbox

not, i was using the multiplayer mod, but i wasn't on a MP world.

**Comment by kremnev8** [comment]
I'm unable to reproduce the issue with the current version of Blueprint Tweaks
