### ISSUE TITLE
[enhancement]turn off the "popup" text that keeps telling me "undo history cleared!"

### ISSUE THREAD

**Issue by Layarion** [kremnev8/DSP-Mods#68]
Everytime i leave a planet or enter warp drive, i see that damn message popup multiple times in one trip. it's really annoying and i didn't see an option for it in the config.

**Comment by kremnev8** [comment]
The message is obviously meant to notify you that this happened. I believe it’s important enough to be shown like this.
Also you seem to be the only person complaining. As such I see this issue as very low priority.

**Comment by kremnev8** [comment]
Implemented in 1.5.11
