### ISSUE TITLE
[BUG] - Can't open blueprint books

### ISSUE THREAD

**Issue by Jorxx88** [kremnev8/DSP-Mods#70]
**Describe the bug**
Cannot access blueprint books in game.

**To Reproduce**
1. Make a book
2. click and drag a blueprint into it
3. test to see if the book will open

**Expected behavior**
the book would open as normally would. 

**Log files**
Unsure how to get a log file for this.

**Comment by kremnev8** [comment]
I'm unable to reproduce your issue with the current version of the mod
