### ISSUE TITLE
[BUG] - Bug title unable to change speed of Conveyor belt Mk.IV in config file

### ISSUE THREAD

**Issue by newbienoobplayer** [kremnev8/DSP-Mods#72]
the org.kremnev8.plugin.BetterMachines files does not have the value for the Mk.IV

![image](https://github.com/kremnev8/DSP-Mods/assets/138718840/9584312c-0742-4c74-82aa-3a8170744b35)

**Expected behavior**
lets me change speed

**Log files**
[org.kremnev8.plugin.BetterMachines.zip](https://github.com/kremnev8/DSP-Mods/files/12327198/org.kremnev8.plugin.BetterMachines.zip)

**Comment by kremnev8** [comment]
Unfortunately, but I don't take feature requests.
Not that this is easily achievable.
