### ISSUE TITLE
not sure if this is a bug butbelt mk 4 is seems to have the wrong colour

### ISSUE THREAD

**Issue by newbienoobplayer** [kremnev8/DSP-Mods#73]
![Screenshot (350)](https://github.com/kremnev8/DSP-Mods/assets/138718840/1d9b8476-9810-416c-84bd-f73c819a6fac)
![Screenshot (349)](https://github.com/kremnev8/DSP-Mods/assets/138718840/52c64494-053b-433d-b031-d2c50faaae76)

**Comment by kremnev8** [comment]
Please provide more info on why you think there is any issues? As far as I see, you are upgrading mk3 belt to mk4, and everything looks correct.
Also any wrong colors do not break the mod functionality, and as such are low priority for me.

**Comment by newbienoobplayer** [comment]
no, in the picture the belt is already mk 4  i am not updating it from mk 3
to mk 4

it is already updated to mk llll,  the speed is the correct speed, but the
color seems to be the colour of mk 3

**Comment by newbienoobplayer** [comment]
I will upload more pictures later on the day as I am busy right now,

**Comment by newbienoobplayer** [comment]
This mod is great though, especially the giga tower so I will be try to
report the issue later on

**Comment by newbienoobplayer** [comment]
so

![Screenshot (358)](https://github.com/kremnev8/DSP-Mods/assets/138718840/aa150a0b-3de9-4c5d-a2d1-d82a26a25a74)
![Screenshot (357)](https://github.com/kremnev8/DSP-Mods/assets/138718840/a347148c-cdf0-446a-85ff-76678eaa9408)
