### ISSUE TITLE
[BUG] - Startup error after patch

### ISSUE THREAD

**Issue by Gimbalhawk** [kremnev8/DSP-Mods#78]
**Describe the bug**
After the recent Dark Fog update BlueprintTweaks causes an error when launching the game

**To Reproduce**
1. Launch the game with BlueprintTweaks enabled
2. See error message in upper right corner
3. Game loading will stall

**Expected behavior**
You should be able to launch the game 

**Log files**
[LogOutput.log](https://github.com/kremnev8/DSP-Mods/files/13692092/LogOutput.log)

**Screenshots**
![BPTweaks Error](https://github.com/kremnev8/DSP-Mods/assets/5201499/1f9ed1a3-8ba7-4109-975a-c5e4f373d76d)

**Comment by kremnev8** [comment]
Hello. I'm aware of the issue. Please wait for a fix.

**Comment by Chemie99** [comment]
I am so glad you are still active kremnev8...this is the most important blueprints of them all...

**Comment by kremnev8** [comment]
I was never gone. Just the game no longer interested me. In the mean time I was modding Core Keeper: https://mod.io/g/corekeeper

**Comment by Chemie99** [comment]
CommonAPI got fixed just now, not sure that helps

**Comment by kremnev8** [comment]
This issue is resolved in 1.5.10. Please also ensure Common API is updated.

**Comment by Gimbalhawk** [comment]
Thank you!
