### ISSUE TITLE
[BUG] - Blueprint Tweaks - Crash when pressing Print (CTRL+P) on keyboard.

### ISSUE THREAD

**Issue by JamieRCHI** [kremnev8/DSP-Mods#8]
Bug Description:
On my keyboard, (Microsoft Natural Ergonometric model 4000, v1.0), if I press the Print key, which is the alternate key for F12, I get NullReferenceException.  (Print is CTRL-P with my keyboard.)

Please note that I think this may be a bug with the DSP game, and not specifically your mod.

Edit: Note that the Print function on my keyboard is bound to CTRL+P.
1. Normally the Function lock key is enabled, and is located to the right of F12.
2. If I 'Accidentally' click on the Function lock key next to F12, the F12 will now function as 'Print'.
3. If I then press what was F12, which is now Print, I get the NullReference Exception. 
4. The error from the output_log.txt file and displayed on the screen:

NullReferenceException: Object reference not set to an instance of an object
  at BlueprintTweaks.GridSnappingPatches.GetGroundCastPos () [0x00030] in <4b12ea7f8e224991aa9a978629650725>:0 
  at BlueprintTweaks.GridSnappingPatches.LockLongtitude () [0x0000e] in <4b12ea7f8e224991aa9a978629650725>:0 
  at BlueprintTweaks.BlueprintTweaksPlugin.Update () [0x0004b] in <4b12ea7f8e224991aa9a978629650725>:0 

Expected behavior:
If the game does not use the Print function (keybind?), nothing should happen.
Also, If the game Does use the Print button for something, I should not get a 
NullReferenceException. 

**Log files**
[output_log.txt](https://github.com/kremnev8/DSP-Mods/files/6912925/output_log.txt)

**Comment by kremnev8** [comment]
Did you bind this modified Print button to Longitude Lock function?

**Comment by kremnev8** [comment]
Also at what state the game is when error happens? Main menu, in game?

**Comment by kremnev8** [comment]
Also can you test this build? Does it fix the error?
[Release.zip](https://github.com/kremnev8/DSP-Mods/files/6912933/Release.zip)

**Comment by JamieRCHI** [comment]
> 
> 
> Did you bind this modified Print button to Longitude Lock function?

No. FPS display was rebound to F12.  It appears that the Print button is CTRL+P and I have that bound to Planet View.

**Comment by JamieRCHI** [comment]
> 
> 
> Also at what state the game is when error happens? Main menu, in game?
In Game.

**Comment by JamieRCHI** [comment]
> 
> 
> Also can you test this build? Does it fix the error?
> [Release.zip](https://github.com/kremnev8/DSP-Mods/files/6912933/Release.zip)
I will try this next. 
In the meantime I believe the 'Lock Latitude Axis' was bound to CTRL-P and I changed it to ALT-P. 
I also changed the 'Open Planet View' from CTRL-P to CTRL-L. Still crashes. 
I shall return shortly after test your new file.

**Comment by kremnev8** [comment]
I think i had an issue during that build. So it might be without the fix. Please try this one:
[Release.zip](https://github.com/kremnev8/DSP-Mods/files/6913007/Release.zip)

**Comment by JamieRCHI** [comment]
Thank you. That fixed it. Now I can use CTRL-P for other stuff.

**Comment by JamieRCHI** [comment]
And Thank You for your help and quick response.
