### ISSUE TITLE
[Enhancement] Auto Place Foundations under ForcePaste/Other condition

### ISSUE THREAD

**Issue by LittleNightmare** [kremnev8/DSP-Mods#86]
although the feature of blueprints with foundations are available, blueprints with foundations are still too rare. it would be even better if we could place the foundation automatly when placing the blueprint.

**Comment by kremnev8** [comment]
Hello. Thanks for your request. I definitely had many people request this feature, so I probably will implement it soon.

**Comment by kremnev8** [comment]
Feature implemented in Blueprint Tweaks v1.6.0
