### ISSUE TITLE
[BUG] - Bug title

### ISSUE THREAD

**Issue by yangyang8599** [kremnev8/DSP-Mods#88]
When pasting blueprint string into existing blueprint you can hold Shift key to keep description and icons

This feature is no longer working，last version it works well. after update it doesnt work。

**Comment by Serverfrog** [comment]
I have the feeling the new version broke a view things, did update through Thunderstore and now its not even possible anymore to change the Items/Recipe from PLS/ILS/Factories, or any other UI Option that was additionally added trough BlueprintTweaks

**Comment by kremnev8** [comment]
This issue is caused, because I forgot to release Common API.
Please update your CommonAPI to v1.6.3
