### ISSUE TITLE
[BUG] 1.6.0 Seems to break everything?

### ISSUE THREAD

**Issue by wallacms** [kremnev8/DSP-Mods#89]
I upgraded to 1.6.0 and all BlueprintTweaks functionality was gone.  I'm using DSP 0.10.28.21247 and I installed via Thunderstore.  Downgrading to 1.5.11 restores the functionality.  The game I loaded was an existing save in Sandbox mode.  Same thing happens with a new game and it seems to happen with or without Sandbox mode enabled.

It seems like the mod isn't being loaded at all because even basic functionality like remembering which folder you were in when you open the blueprint screen doesn't work.

**Comment by Pardonius** [comment]
Some

**Comment by wallacms** [comment]
Fixed by upgrading CommonAPI to 1.6.3
