### ISSUE TITLE
[BUG] - Error pressing lock axis or grid button in a wrong mode

### ISSUE THREAD

**Issue by Lt-Sparky** [kremnev8/DSP-Mods#9]
Making late game final blueprints ant this error keeps popping up....
![BluePrintError](https://user-images.githubusercontent.com/85095233/127959874-db0e4737-8cd7-49ea-b6b5-51cb0e57a3be.jpg)

**Comment by kremnev8** [comment]
This looks like a duplicate of #8. I haven't released a fix for it on thunderstore, but you can take last file from that issue. I will release that fix to thunderstore soon.

**Comment by kremnev8** [comment]
Also fixed in 1.0.8
