### ISSUE TITLE
[BUG] - BlueprintTweaks: Belt hints spawning items, placed on belts that weren't present in the source

### ISSUE THREAD

**Issue by JoeMShanahan** [kremnev8/DSP-Mods#90]
**Describe the bug**
I am attempting to copy a set of smelters and trying to alter the recipe.

The belt hint icon selector appears to be bugged: the size of the panel is wrong and what I visibly click on does not get visibily selected (the visible selection is offset from my mouse) yet when hitting the confirm button what I visibly clicked on IS actually chosen.

![image](https://github.com/kremnev8/DSP-Mods/assets/29176664/c4bb8649-1d42-4bc6-80db-7bc9f9fe3591)

Addtionally, and more problematic is that spurious belt hints seem to be littered across my pasted blueprint. The proliferator juice on the belt here should not be there at all and is being generatoed by _something_ but it's not obvious what as the whole belt has been filled with it. It's showing titanium ore too instead of the copied silicon - a previous attempt was me changing to titanium but despite now copy and pasting an unmodified silicon setup the previous attempt is seemingly still in some temporary state and erroneously appearing here.

![image](https://github.com/kremnev8/DSP-Mods/assets/29176664/1cf22e36-e605-4a48-9766-6572562ce981)

**Comment by JoeMShanahan** [comment]
Noticed that it appears to be these particular map tiles that are bugged. I've loaded up in to vanilla with my save and when manually placing down belts over the bugged area these have appeared.

**Comment by JoeMShanahan** [comment]
So I'm fairly sure I know what happened here. It seems like at some point I'd created a bugged ILS, I determined that the juice was being taken from a certain ILS. After removing that ILS it's no longer happening.

**Comment by kremnev8** [comment]
I'm not sure about the random hints coming from nowhere.
But the picker issue is resolved. Update Common API to v1.6.4
Closing this for now. If you encounter further issues, please open new issue.
