### ISSUE TITLE
[FEATURE] BlueprintTweaks: Add resour inpute outpute calculation

### ISSUE THREAD

**Issue by Zaazik** [kremnev8/DSP-Mods#91]
Add calculation inpute reourse in example 
Blueprint:
     smelters MK1 x 60 
     prliferator MK2
     reciept titan ignots 
     
     
iron recipe 2s = in 2 ore, out 1 ignot
proliferator MK2 = 24 spreys 

inpute: 
      titan ore = (base recept value in minute * smelter product speed * proliferater buff(if enable product speed up)) * smlter count
      titan ore = (60 * 1.0) * 60 = 3600/min
outpute:
      titan ignot =  (base recept value in minute * smelter product speed * proliferater buff(extra product)) * smlter count
      titan ore = (30 * 1.0*1.20) * 60 = 2160/min
      
I think game alredy has final outpute calcucalition by smelter type and buff..
we can just get that namber and multyply all inpute recept and out put recept
![image](https://github.com/kremnev8/DSP-Mods/assets/17027851/24491ead-ee93-4f46-9e48-def270a82ebb)
![image](https://github.com/kremnev8/DSP-Mods/assets/17027851/f6fdbf42-22b1-428b-87c3-0ed8980c6c23)

**Comment by kremnev8** [comment]
First of all, can you please fix your grammar? Your issue text is not readable.
I'm not sure what exactly do you want. And even then this has nothing to do with Blueprint tweaks
