### ISSUE TITLE
[BUG] - Mirror Image drops some PLS/ILS input or output designations

### ISSUE THREAD

**Issue by Chemie99** [kremnev8/DSP-Mods#95]
When using the mirror image function, the PLS or ILS loses some of the output designations.

**To Reproduce**
1. Select Blueprint
2. Shift-T for mirror image
3. Paste
4. No output for an item that is there when normal paste is used (works when the output is reselected again); Also applies to inputs where the belt has to be deleted and re-connected to ILS for flow.

Re-copied and saved below BP with working output for titanium and it still did same thing.
Note: In the two cases I tested (one out and one input) it was always the same position that was broken. When looking at PLS, the 1 o'clock port was the one broken for both input and output (2 different BPs)

**Expected behavior**
Keep the output that was assigned to that belt

Normal: (See Ti output on left)
![image](https://github.com/kremnev8/DSP-Mods/assets/94768495/1c775dbe-fb02-4177-ac10-41137610ebe2)

Mirror (missing Titanium output on right)
![image](https://github.com/kremnev8/DSP-Mods/assets/94768495/5fbb6022-d6c5-4f60-b16b-b2db937d5ef8)

Example Blueprint:
BLUEPRINT:0,32,1106,6003,1115,0,0,0,638231214054714724,0.9.27.15466,Add-On%20Titanium%20Yellow,PLS%20add%20on%20for%20Titanium%20for%20yellow%20%28titanium%20crystals%29%20and%20plastic"H4sIAAAAAAAAC+2aMWgTURzG36Vpc02btE0TsKitg6KDS4kQTA7umXPRQaSCoKW4WOkknQTjEEFJSnGwSyFgiB3sICJqQxOoQ7fGTUTHYEEHQSqClEoonu8778wfexU3Rf4/+I7vLu9779373yPDnSaECLoC3Uq66zVhC9FwL+si4V4WR+y8PCSk1O4OpajfvFXNQq9CB0WPamcrNHTzsz/Fov1W5leuprTpKzXqty89tSCEAzvCATEe9Jxiak9TJi7kzGSyblA/PPfMgtCJ7jODDhwKtin3ilWJUan3GpX0o04QCELQu/esuO8EqH8+vWBBGHnAZ+ROHDJvluWDRkVOXosb1IdfFywI4S7VLobF6mjf+5h77/hNRPSSrJcrMnmjblA/tb9oQegk6DODkHfvx1Gu1aFl6h/1VLMQwsJn9SfcGTiPRk1ryvn4hjm5GDeo//JhyYLQScztpIvMAM+WWFOLNizWnQeG+vm5sgUh3Ocz/TAODw+P1MNugPqzgaIFIUxKt2MB8VSK9c8laVw3ZfJjzaB+NFPNQugk7jODXhxmvtnmAYyqak79e7tgQQhHfMIRp4ftvOlNmfotFdxyw2GfcPTHwtlqs3xKoVzUnyy/S0EI9/uUzts4fV79Mxj13qk69UFRtCB00uszg35vBgtVtdNWKgb1rcdjaQjhQZ/wgLdxou5Oo/7Y7O00hHC3Gw6QcMwbOSFuOgHqvUYpfdRvy+qoe8A9eRJs/4A18UaYGWxfn9jlOsP8r2i/eG23hqK9l/70nPm7vGyq/9+RcEvsOxN16nou5NT3otJl0u53NWcYhmEYhmEYhmEYhmEYhmEYhmGYfwXnFT4+GPh6YsN8caeRof58azYN0c9VQuRdGL4BEadzNbm5Zjqf6VCfG1/KQjTcScLfAZpDX7xYJQAA"45A994BABF35D14B3F6E410493B50695

**Comment by kremnev8** [comment]
Thanks for your report. I’m aware of the issue, will address it soon.
This issue came about from my belt ports fix. So unfortunately one bug fixed, caused a new one.

**Comment by Chemie99** [comment]
Thanks for the note; I was about to do a bunch more troubleshooting (was wondering if order the belt were attached mattered and which ports broke).  Saves me that testing so thanks.

**Comment by kremnev8** [comment]
Issue has been fixed in v1.6.2

**Comment by Chemie99** [comment]
Thanks for the fast fix!  This is my #1 mod.
