### ISSUE TITLE
[BUG] - Better machines

### ISSUE THREAD

**Issue by AandD** [kremnev8/DSP-Mods#99]
**Describe the bug**
Building drone replaced with t4 storage. So instead of building it build hologram and places storage then does nothing.

**To Reproduce**
1. New game
2. build something
3. See error

**Expected behavior**
Dron normally builds

**Screenshots**
![image](https://github.com/kremnev8/DSP-Mods/assets/35153/2d9970fb-a621-4dcd-9ab7-957c8dbf45e2)

**Comment by kremnev8** [comment]
Known issue. Duplicate of #94
